[package]
name = "isometric_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = { version = "0.4.11", features = ["log"] }
# impacted = "2.0.2"
# parry2d = "0.16.1"
