name: Build & Run Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    name: Checkout
    uses: actions/checkout@v4
    name: Install Rust toolchain
    uses: dtolnay/rust-toolchain@stable
    with:
      target: wasm32-unknown-unknown
    # name: Install Server
    # uses: baptiste0928/cargo-install@v3
    # with:
    #   crate: basic-http-server
    name: Build
    run: cargo build --release --target wasm32-unknown-unknown
    name: serve
    run: basic-http-server .
    name: Deploy to GitHub Pages
    uses: crazy-max/ghaction-github-pages@v4
    with:
      target_branch: gh-pages
      build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
